/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojEventsV1alpha1Service struct for IoArgoprojEventsV1alpha1Service
type IoArgoprojEventsV1alpha1Service struct {
	ClusterIP *string `json:"clusterIP,omitempty"`
	Ports *[]IoK8sApiCoreV1ServicePort `json:"ports,omitempty"`
}

// NewIoArgoprojEventsV1alpha1Service instantiates a new IoArgoprojEventsV1alpha1Service object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojEventsV1alpha1Service() *IoArgoprojEventsV1alpha1Service {
	this := IoArgoprojEventsV1alpha1Service{}
	return &this
}

// NewIoArgoprojEventsV1alpha1ServiceWithDefaults instantiates a new IoArgoprojEventsV1alpha1Service object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojEventsV1alpha1ServiceWithDefaults() *IoArgoprojEventsV1alpha1Service {
	this := IoArgoprojEventsV1alpha1Service{}
	return &this
}

// GetClusterIP returns the ClusterIP field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1Service) GetClusterIP() string {
	if o == nil || o.ClusterIP == nil {
		var ret string
		return ret
	}
	return *o.ClusterIP
}

// GetClusterIPOk returns a tuple with the ClusterIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1Service) GetClusterIPOk() (*string, bool) {
	if o == nil || o.ClusterIP == nil {
		return nil, false
	}
	return o.ClusterIP, true
}

// HasClusterIP returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1Service) HasClusterIP() bool {
	if o != nil && o.ClusterIP != nil {
		return true
	}

	return false
}

// SetClusterIP gets a reference to the given string and assigns it to the ClusterIP field.
func (o *IoArgoprojEventsV1alpha1Service) SetClusterIP(v string) {
	o.ClusterIP = &v
}

// GetPorts returns the Ports field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1Service) GetPorts() []IoK8sApiCoreV1ServicePort {
	if o == nil || o.Ports == nil {
		var ret []IoK8sApiCoreV1ServicePort
		return ret
	}
	return *o.Ports
}

// GetPortsOk returns a tuple with the Ports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1Service) GetPortsOk() (*[]IoK8sApiCoreV1ServicePort, bool) {
	if o == nil || o.Ports == nil {
		return nil, false
	}
	return o.Ports, true
}

// HasPorts returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1Service) HasPorts() bool {
	if o != nil && o.Ports != nil {
		return true
	}

	return false
}

// SetPorts gets a reference to the given []IoK8sApiCoreV1ServicePort and assigns it to the Ports field.
func (o *IoArgoprojEventsV1alpha1Service) SetPorts(v []IoK8sApiCoreV1ServicePort) {
	o.Ports = &v
}

func (o IoArgoprojEventsV1alpha1Service) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClusterIP != nil {
		toSerialize["clusterIP"] = o.ClusterIP
	}
	if o.Ports != nil {
		toSerialize["ports"] = o.Ports
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojEventsV1alpha1Service struct {
	value *IoArgoprojEventsV1alpha1Service
	isSet bool
}

func (v NullableIoArgoprojEventsV1alpha1Service) Get() *IoArgoprojEventsV1alpha1Service {
	return v.value
}

func (v *NullableIoArgoprojEventsV1alpha1Service) Set(val *IoArgoprojEventsV1alpha1Service) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojEventsV1alpha1Service) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojEventsV1alpha1Service) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojEventsV1alpha1Service(val *IoArgoprojEventsV1alpha1Service) *NullableIoArgoprojEventsV1alpha1Service {
	return &NullableIoArgoprojEventsV1alpha1Service{value: val, isSet: true}
}

func (v NullableIoArgoprojEventsV1alpha1Service) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojEventsV1alpha1Service) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


