/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoK8sApiCoreV1ConfigMapKeySelector Selects a key from a ConfigMap.
type IoK8sApiCoreV1ConfigMapKeySelector struct {
	// The key to select.
	Key string `json:"key"`
	// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the ConfigMap or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// NewIoK8sApiCoreV1ConfigMapKeySelector instantiates a new IoK8sApiCoreV1ConfigMapKeySelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoK8sApiCoreV1ConfigMapKeySelector(key string) *IoK8sApiCoreV1ConfigMapKeySelector {
	this := IoK8sApiCoreV1ConfigMapKeySelector{}
	this.Key = key
	return &this
}

// NewIoK8sApiCoreV1ConfigMapKeySelectorWithDefaults instantiates a new IoK8sApiCoreV1ConfigMapKeySelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoK8sApiCoreV1ConfigMapKeySelectorWithDefaults() *IoK8sApiCoreV1ConfigMapKeySelector {
	this := IoK8sApiCoreV1ConfigMapKeySelector{}
	return &this
}

// GetKey returns the Key field value
func (o *IoK8sApiCoreV1ConfigMapKeySelector) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) GetKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *IoK8sApiCoreV1ConfigMapKeySelector) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) SetName(v string) {
	o.Name = &v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) GetOptional() bool {
	if o == nil || o.Optional == nil {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) GetOptionalOk() (*bool, bool) {
	if o == nil || o.Optional == nil {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) HasOptional() bool {
	if o != nil && o.Optional != nil {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *IoK8sApiCoreV1ConfigMapKeySelector) SetOptional(v bool) {
	o.Optional = &v
}

func (o IoK8sApiCoreV1ConfigMapKeySelector) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Optional != nil {
		toSerialize["optional"] = o.Optional
	}
	return json.Marshal(toSerialize)
}

type NullableIoK8sApiCoreV1ConfigMapKeySelector struct {
	value *IoK8sApiCoreV1ConfigMapKeySelector
	isSet bool
}

func (v NullableIoK8sApiCoreV1ConfigMapKeySelector) Get() *IoK8sApiCoreV1ConfigMapKeySelector {
	return v.value
}

func (v *NullableIoK8sApiCoreV1ConfigMapKeySelector) Set(val *IoK8sApiCoreV1ConfigMapKeySelector) {
	v.value = val
	v.isSet = true
}

func (v NullableIoK8sApiCoreV1ConfigMapKeySelector) IsSet() bool {
	return v.isSet
}

func (v *NullableIoK8sApiCoreV1ConfigMapKeySelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoK8sApiCoreV1ConfigMapKeySelector(val *IoK8sApiCoreV1ConfigMapKeySelector) *NullableIoK8sApiCoreV1ConfigMapKeySelector {
	return &NullableIoK8sApiCoreV1ConfigMapKeySelector{value: val, isSet: true}
}

func (v NullableIoK8sApiCoreV1ConfigMapKeySelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoK8sApiCoreV1ConfigMapKeySelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


