/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig struct for IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig
type IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig struct {
	AutoDelete *bool `json:"autoDelete,omitempty"`
	Durable *bool `json:"durable,omitempty"`
	Exclusive *bool `json:"exclusive,omitempty"`
	Name *string `json:"name,omitempty"`
	NoWait *bool `json:"noWait,omitempty"`
}

// NewIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig instantiates a new IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig() *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig {
	this := IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig{}
	return &this
}

// NewIoArgoprojEventsV1alpha1AMQPQueueDeclareConfigWithDefaults instantiates a new IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojEventsV1alpha1AMQPQueueDeclareConfigWithDefaults() *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig {
	this := IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig{}
	return &this
}

// GetAutoDelete returns the AutoDelete field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetAutoDelete() bool {
	if o == nil || o.AutoDelete == nil {
		var ret bool
		return ret
	}
	return *o.AutoDelete
}

// GetAutoDeleteOk returns a tuple with the AutoDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetAutoDeleteOk() (*bool, bool) {
	if o == nil || o.AutoDelete == nil {
		return nil, false
	}
	return o.AutoDelete, true
}

// HasAutoDelete returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) HasAutoDelete() bool {
	if o != nil && o.AutoDelete != nil {
		return true
	}

	return false
}

// SetAutoDelete gets a reference to the given bool and assigns it to the AutoDelete field.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) SetAutoDelete(v bool) {
	o.AutoDelete = &v
}

// GetDurable returns the Durable field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetDurable() bool {
	if o == nil || o.Durable == nil {
		var ret bool
		return ret
	}
	return *o.Durable
}

// GetDurableOk returns a tuple with the Durable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetDurableOk() (*bool, bool) {
	if o == nil || o.Durable == nil {
		return nil, false
	}
	return o.Durable, true
}

// HasDurable returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) HasDurable() bool {
	if o != nil && o.Durable != nil {
		return true
	}

	return false
}

// SetDurable gets a reference to the given bool and assigns it to the Durable field.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) SetDurable(v bool) {
	o.Durable = &v
}

// GetExclusive returns the Exclusive field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetExclusive() bool {
	if o == nil || o.Exclusive == nil {
		var ret bool
		return ret
	}
	return *o.Exclusive
}

// GetExclusiveOk returns a tuple with the Exclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetExclusiveOk() (*bool, bool) {
	if o == nil || o.Exclusive == nil {
		return nil, false
	}
	return o.Exclusive, true
}

// HasExclusive returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) HasExclusive() bool {
	if o != nil && o.Exclusive != nil {
		return true
	}

	return false
}

// SetExclusive gets a reference to the given bool and assigns it to the Exclusive field.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) SetExclusive(v bool) {
	o.Exclusive = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) SetName(v string) {
	o.Name = &v
}

// GetNoWait returns the NoWait field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetNoWait() bool {
	if o == nil || o.NoWait == nil {
		var ret bool
		return ret
	}
	return *o.NoWait
}

// GetNoWaitOk returns a tuple with the NoWait field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) GetNoWaitOk() (*bool, bool) {
	if o == nil || o.NoWait == nil {
		return nil, false
	}
	return o.NoWait, true
}

// HasNoWait returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) HasNoWait() bool {
	if o != nil && o.NoWait != nil {
		return true
	}

	return false
}

// SetNoWait gets a reference to the given bool and assigns it to the NoWait field.
func (o *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) SetNoWait(v bool) {
	o.NoWait = &v
}

func (o IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AutoDelete != nil {
		toSerialize["autoDelete"] = o.AutoDelete
	}
	if o.Durable != nil {
		toSerialize["durable"] = o.Durable
	}
	if o.Exclusive != nil {
		toSerialize["exclusive"] = o.Exclusive
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.NoWait != nil {
		toSerialize["noWait"] = o.NoWait
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig struct {
	value *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig
	isSet bool
}

func (v NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) Get() *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig {
	return v.value
}

func (v *NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) Set(val *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig(val *IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) *NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig {
	return &NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig{value: val, isSet: true}
}

func (v NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


