/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep struct for GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep
type GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep struct {
	Resources *IoK8sApiCoreV1ResourceRequirements `json:"resources,omitempty"`
}

// NewGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep instantiates a new GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep() *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep {
	this := GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep{}
	return &this
}

// NewGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStepWithDefaults instantiates a new GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStepWithDefaults() *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep {
	this := GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep{}
	return &this
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) GetResources() IoK8sApiCoreV1ResourceRequirements {
	if o == nil || o.Resources == nil {
		var ret IoK8sApiCoreV1ResourceRequirements
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) GetResourcesOk() (*IoK8sApiCoreV1ResourceRequirements, bool) {
	if o == nil || o.Resources == nil {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) HasResources() bool {
	if o != nil && o.Resources != nil {
		return true
	}

	return false
}

// SetResources gets a reference to the given IoK8sApiCoreV1ResourceRequirements and assigns it to the Resources field.
func (o *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) SetResources(v IoK8sApiCoreV1ResourceRequirements) {
	o.Resources = &v
}

func (o GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Resources != nil {
		toSerialize["resources"] = o.Resources
	}
	return json.Marshal(toSerialize)
}

type NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep struct {
	value *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep
	isSet bool
}

func (v NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) Get() *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep {
	return v.value
}

func (v *NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) Set(val *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep(val *GithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) *NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep {
	return &NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep{value: val, isSet: true}
}

func (v NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComArgoprojLabsArgoDataflowApiV1alpha1AbstractStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


