/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojWorkflowV1alpha1Template Template is a reusable and composable unit of execution in a workflow
type IoArgoprojWorkflowV1alpha1Template struct {
	ActiveDeadlineSeconds *string `json:"activeDeadlineSeconds,omitempty"`
	Affinity *IoK8sApiCoreV1Affinity `json:"affinity,omitempty"`
	ArchiveLocation *IoArgoprojWorkflowV1alpha1ArtifactLocation `json:"archiveLocation,omitempty"`
	// AutomountServiceAccountToken indicates whether a service account token should be automatically mounted in pods. ServiceAccountName of ExecutorConfig must be specified if this value is false.
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty"`
	Container *IoK8sApiCoreV1Container `json:"container,omitempty"`
	ContainerSet *IoArgoprojWorkflowV1alpha1ContainerSetTemplate `json:"containerSet,omitempty"`
	// Deamon will allow a workflow to proceed to the next step so long as the container reaches readiness
	Daemon *bool `json:"daemon,omitempty"`
	Dag *IoArgoprojWorkflowV1alpha1DAGTemplate `json:"dag,omitempty"`
	Data *IoArgoprojWorkflowV1alpha1Data `json:"data,omitempty"`
	Executor *IoArgoprojWorkflowV1alpha1ExecutorConfig `json:"executor,omitempty"`
	// FailFast, if specified, will fail this template if any of its child pods has failed. This is useful for when this template is expanded with `withItems`, etc.
	FailFast *bool `json:"failFast,omitempty"`
	// HostAliases is an optional list of hosts and IPs that will be injected into the pod spec
	HostAliases *[]IoK8sApiCoreV1HostAlias `json:"hostAliases,omitempty"`
	Http *IoArgoprojWorkflowV1alpha1HTTP `json:"http,omitempty"`
	// InitContainers is a list of containers which run before the main container.
	InitContainers *[]IoArgoprojWorkflowV1alpha1UserContainer `json:"initContainers,omitempty"`
	Inputs *IoArgoprojWorkflowV1alpha1Inputs `json:"inputs,omitempty"`
	Memoize *IoArgoprojWorkflowV1alpha1Memoize `json:"memoize,omitempty"`
	Metadata *IoArgoprojWorkflowV1alpha1Metadata `json:"metadata,omitempty"`
	Metrics *IoArgoprojWorkflowV1alpha1Metrics `json:"metrics,omitempty"`
	// Name is the name of the template
	Name *string `json:"name,omitempty"`
	// NodeSelector is a selector to schedule this step of the workflow to be run on the selected node(s). Overrides the selector set at the workflow level.
	NodeSelector *map[string]string `json:"nodeSelector,omitempty"`
	Outputs *IoArgoprojWorkflowV1alpha1Outputs `json:"outputs,omitempty"`
	// Parallelism limits the max total parallel pods that can execute at the same time within the boundaries of this template invocation. If additional steps/dag templates are invoked, the pods created by those templates will not be counted towards this total.
	Parallelism *int32 `json:"parallelism,omitempty"`
	// PodSpecPatch holds strategic merge patch to apply against the pod spec. Allows parameterization of container fields which are not strings (e.g. resource limits).
	PodSpecPatch *string `json:"podSpecPatch,omitempty"`
	// Priority to apply to workflow pods.
	Priority *int32 `json:"priority,omitempty"`
	// PriorityClassName to apply to workflow pods.
	PriorityClassName *string `json:"priorityClassName,omitempty"`
	Resource *IoArgoprojWorkflowV1alpha1ResourceTemplate `json:"resource,omitempty"`
	RetryStrategy *IoArgoprojWorkflowV1alpha1RetryStrategy `json:"retryStrategy,omitempty"`
	// If specified, the pod will be dispatched by specified scheduler. Or it will be dispatched by workflow scope scheduler if specified. If neither specified, the pod will be dispatched by default scheduler.
	SchedulerName *string `json:"schedulerName,omitempty"`
	Script *IoArgoprojWorkflowV1alpha1ScriptTemplate `json:"script,omitempty"`
	SecurityContext *IoK8sApiCoreV1PodSecurityContext `json:"securityContext,omitempty"`
	// ServiceAccountName to apply to workflow pods
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
	// Sidecars is a list of containers which run alongside the main container Sidecars are automatically killed when the main container completes
	Sidecars *[]IoArgoprojWorkflowV1alpha1UserContainer `json:"sidecars,omitempty"`
	// Steps define a series of sequential/parallel workflow steps
	Steps *[][]IoArgoprojWorkflowV1alpha1WorkflowStep `json:"steps,omitempty"`
	Suspend *IoArgoprojWorkflowV1alpha1SuspendTemplate `json:"suspend,omitempty"`
	Synchronization *IoArgoprojWorkflowV1alpha1Synchronization `json:"synchronization,omitempty"`
	// Timout allows to set the total node execution timeout duration counting from the node's start time. This duration also includes time in which the node spends in Pending state. This duration may not be applied to Step or DAG templates.
	Timeout *string `json:"timeout,omitempty"`
	// Tolerations to apply to workflow pods.
	Tolerations *[]IoK8sApiCoreV1Toleration `json:"tolerations,omitempty"`
	// Volumes is a list of volumes that can be mounted by containers in a template.
	Volumes *[]IoK8sApiCoreV1Volume `json:"volumes,omitempty"`
}

// NewIoArgoprojWorkflowV1alpha1Template instantiates a new IoArgoprojWorkflowV1alpha1Template object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojWorkflowV1alpha1Template() *IoArgoprojWorkflowV1alpha1Template {
	this := IoArgoprojWorkflowV1alpha1Template{}
	return &this
}

// NewIoArgoprojWorkflowV1alpha1TemplateWithDefaults instantiates a new IoArgoprojWorkflowV1alpha1Template object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojWorkflowV1alpha1TemplateWithDefaults() *IoArgoprojWorkflowV1alpha1Template {
	this := IoArgoprojWorkflowV1alpha1Template{}
	return &this
}

// GetActiveDeadlineSeconds returns the ActiveDeadlineSeconds field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetActiveDeadlineSeconds() string {
	if o == nil || o.ActiveDeadlineSeconds == nil {
		var ret string
		return ret
	}
	return *o.ActiveDeadlineSeconds
}

// GetActiveDeadlineSecondsOk returns a tuple with the ActiveDeadlineSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetActiveDeadlineSecondsOk() (*string, bool) {
	if o == nil || o.ActiveDeadlineSeconds == nil {
		return nil, false
	}
	return o.ActiveDeadlineSeconds, true
}

// HasActiveDeadlineSeconds returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasActiveDeadlineSeconds() bool {
	if o != nil && o.ActiveDeadlineSeconds != nil {
		return true
	}

	return false
}

// SetActiveDeadlineSeconds gets a reference to the given string and assigns it to the ActiveDeadlineSeconds field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetActiveDeadlineSeconds(v string) {
	o.ActiveDeadlineSeconds = &v
}

// GetAffinity returns the Affinity field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetAffinity() IoK8sApiCoreV1Affinity {
	if o == nil || o.Affinity == nil {
		var ret IoK8sApiCoreV1Affinity
		return ret
	}
	return *o.Affinity
}

// GetAffinityOk returns a tuple with the Affinity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetAffinityOk() (*IoK8sApiCoreV1Affinity, bool) {
	if o == nil || o.Affinity == nil {
		return nil, false
	}
	return o.Affinity, true
}

// HasAffinity returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasAffinity() bool {
	if o != nil && o.Affinity != nil {
		return true
	}

	return false
}

// SetAffinity gets a reference to the given IoK8sApiCoreV1Affinity and assigns it to the Affinity field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetAffinity(v IoK8sApiCoreV1Affinity) {
	o.Affinity = &v
}

// GetArchiveLocation returns the ArchiveLocation field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetArchiveLocation() IoArgoprojWorkflowV1alpha1ArtifactLocation {
	if o == nil || o.ArchiveLocation == nil {
		var ret IoArgoprojWorkflowV1alpha1ArtifactLocation
		return ret
	}
	return *o.ArchiveLocation
}

// GetArchiveLocationOk returns a tuple with the ArchiveLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetArchiveLocationOk() (*IoArgoprojWorkflowV1alpha1ArtifactLocation, bool) {
	if o == nil || o.ArchiveLocation == nil {
		return nil, false
	}
	return o.ArchiveLocation, true
}

// HasArchiveLocation returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasArchiveLocation() bool {
	if o != nil && o.ArchiveLocation != nil {
		return true
	}

	return false
}

// SetArchiveLocation gets a reference to the given IoArgoprojWorkflowV1alpha1ArtifactLocation and assigns it to the ArchiveLocation field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetArchiveLocation(v IoArgoprojWorkflowV1alpha1ArtifactLocation) {
	o.ArchiveLocation = &v
}

// GetAutomountServiceAccountToken returns the AutomountServiceAccountToken field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetAutomountServiceAccountToken() bool {
	if o == nil || o.AutomountServiceAccountToken == nil {
		var ret bool
		return ret
	}
	return *o.AutomountServiceAccountToken
}

// GetAutomountServiceAccountTokenOk returns a tuple with the AutomountServiceAccountToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetAutomountServiceAccountTokenOk() (*bool, bool) {
	if o == nil || o.AutomountServiceAccountToken == nil {
		return nil, false
	}
	return o.AutomountServiceAccountToken, true
}

// HasAutomountServiceAccountToken returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasAutomountServiceAccountToken() bool {
	if o != nil && o.AutomountServiceAccountToken != nil {
		return true
	}

	return false
}

// SetAutomountServiceAccountToken gets a reference to the given bool and assigns it to the AutomountServiceAccountToken field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetAutomountServiceAccountToken(v bool) {
	o.AutomountServiceAccountToken = &v
}

// GetContainer returns the Container field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetContainer() IoK8sApiCoreV1Container {
	if o == nil || o.Container == nil {
		var ret IoK8sApiCoreV1Container
		return ret
	}
	return *o.Container
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetContainerOk() (*IoK8sApiCoreV1Container, bool) {
	if o == nil || o.Container == nil {
		return nil, false
	}
	return o.Container, true
}

// HasContainer returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasContainer() bool {
	if o != nil && o.Container != nil {
		return true
	}

	return false
}

// SetContainer gets a reference to the given IoK8sApiCoreV1Container and assigns it to the Container field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetContainer(v IoK8sApiCoreV1Container) {
	o.Container = &v
}

// GetContainerSet returns the ContainerSet field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetContainerSet() IoArgoprojWorkflowV1alpha1ContainerSetTemplate {
	if o == nil || o.ContainerSet == nil {
		var ret IoArgoprojWorkflowV1alpha1ContainerSetTemplate
		return ret
	}
	return *o.ContainerSet
}

// GetContainerSetOk returns a tuple with the ContainerSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetContainerSetOk() (*IoArgoprojWorkflowV1alpha1ContainerSetTemplate, bool) {
	if o == nil || o.ContainerSet == nil {
		return nil, false
	}
	return o.ContainerSet, true
}

// HasContainerSet returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasContainerSet() bool {
	if o != nil && o.ContainerSet != nil {
		return true
	}

	return false
}

// SetContainerSet gets a reference to the given IoArgoprojWorkflowV1alpha1ContainerSetTemplate and assigns it to the ContainerSet field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetContainerSet(v IoArgoprojWorkflowV1alpha1ContainerSetTemplate) {
	o.ContainerSet = &v
}

// GetDaemon returns the Daemon field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetDaemon() bool {
	if o == nil || o.Daemon == nil {
		var ret bool
		return ret
	}
	return *o.Daemon
}

// GetDaemonOk returns a tuple with the Daemon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetDaemonOk() (*bool, bool) {
	if o == nil || o.Daemon == nil {
		return nil, false
	}
	return o.Daemon, true
}

// HasDaemon returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasDaemon() bool {
	if o != nil && o.Daemon != nil {
		return true
	}

	return false
}

// SetDaemon gets a reference to the given bool and assigns it to the Daemon field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetDaemon(v bool) {
	o.Daemon = &v
}

// GetDag returns the Dag field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetDag() IoArgoprojWorkflowV1alpha1DAGTemplate {
	if o == nil || o.Dag == nil {
		var ret IoArgoprojWorkflowV1alpha1DAGTemplate
		return ret
	}
	return *o.Dag
}

// GetDagOk returns a tuple with the Dag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetDagOk() (*IoArgoprojWorkflowV1alpha1DAGTemplate, bool) {
	if o == nil || o.Dag == nil {
		return nil, false
	}
	return o.Dag, true
}

// HasDag returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasDag() bool {
	if o != nil && o.Dag != nil {
		return true
	}

	return false
}

// SetDag gets a reference to the given IoArgoprojWorkflowV1alpha1DAGTemplate and assigns it to the Dag field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetDag(v IoArgoprojWorkflowV1alpha1DAGTemplate) {
	o.Dag = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetData() IoArgoprojWorkflowV1alpha1Data {
	if o == nil || o.Data == nil {
		var ret IoArgoprojWorkflowV1alpha1Data
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetDataOk() (*IoArgoprojWorkflowV1alpha1Data, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given IoArgoprojWorkflowV1alpha1Data and assigns it to the Data field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetData(v IoArgoprojWorkflowV1alpha1Data) {
	o.Data = &v
}

// GetExecutor returns the Executor field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetExecutor() IoArgoprojWorkflowV1alpha1ExecutorConfig {
	if o == nil || o.Executor == nil {
		var ret IoArgoprojWorkflowV1alpha1ExecutorConfig
		return ret
	}
	return *o.Executor
}

// GetExecutorOk returns a tuple with the Executor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetExecutorOk() (*IoArgoprojWorkflowV1alpha1ExecutorConfig, bool) {
	if o == nil || o.Executor == nil {
		return nil, false
	}
	return o.Executor, true
}

// HasExecutor returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasExecutor() bool {
	if o != nil && o.Executor != nil {
		return true
	}

	return false
}

// SetExecutor gets a reference to the given IoArgoprojWorkflowV1alpha1ExecutorConfig and assigns it to the Executor field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetExecutor(v IoArgoprojWorkflowV1alpha1ExecutorConfig) {
	o.Executor = &v
}

// GetFailFast returns the FailFast field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetFailFast() bool {
	if o == nil || o.FailFast == nil {
		var ret bool
		return ret
	}
	return *o.FailFast
}

// GetFailFastOk returns a tuple with the FailFast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetFailFastOk() (*bool, bool) {
	if o == nil || o.FailFast == nil {
		return nil, false
	}
	return o.FailFast, true
}

// HasFailFast returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasFailFast() bool {
	if o != nil && o.FailFast != nil {
		return true
	}

	return false
}

// SetFailFast gets a reference to the given bool and assigns it to the FailFast field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetFailFast(v bool) {
	o.FailFast = &v
}

// GetHostAliases returns the HostAliases field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetHostAliases() []IoK8sApiCoreV1HostAlias {
	if o == nil || o.HostAliases == nil {
		var ret []IoK8sApiCoreV1HostAlias
		return ret
	}
	return *o.HostAliases
}

// GetHostAliasesOk returns a tuple with the HostAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetHostAliasesOk() (*[]IoK8sApiCoreV1HostAlias, bool) {
	if o == nil || o.HostAliases == nil {
		return nil, false
	}
	return o.HostAliases, true
}

// HasHostAliases returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasHostAliases() bool {
	if o != nil && o.HostAliases != nil {
		return true
	}

	return false
}

// SetHostAliases gets a reference to the given []IoK8sApiCoreV1HostAlias and assigns it to the HostAliases field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetHostAliases(v []IoK8sApiCoreV1HostAlias) {
	o.HostAliases = &v
}

// GetHttp returns the Http field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetHttp() IoArgoprojWorkflowV1alpha1HTTP {
	if o == nil || o.Http == nil {
		var ret IoArgoprojWorkflowV1alpha1HTTP
		return ret
	}
	return *o.Http
}

// GetHttpOk returns a tuple with the Http field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetHttpOk() (*IoArgoprojWorkflowV1alpha1HTTP, bool) {
	if o == nil || o.Http == nil {
		return nil, false
	}
	return o.Http, true
}

// HasHttp returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasHttp() bool {
	if o != nil && o.Http != nil {
		return true
	}

	return false
}

// SetHttp gets a reference to the given IoArgoprojWorkflowV1alpha1HTTP and assigns it to the Http field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetHttp(v IoArgoprojWorkflowV1alpha1HTTP) {
	o.Http = &v
}

// GetInitContainers returns the InitContainers field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetInitContainers() []IoArgoprojWorkflowV1alpha1UserContainer {
	if o == nil || o.InitContainers == nil {
		var ret []IoArgoprojWorkflowV1alpha1UserContainer
		return ret
	}
	return *o.InitContainers
}

// GetInitContainersOk returns a tuple with the InitContainers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetInitContainersOk() (*[]IoArgoprojWorkflowV1alpha1UserContainer, bool) {
	if o == nil || o.InitContainers == nil {
		return nil, false
	}
	return o.InitContainers, true
}

// HasInitContainers returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasInitContainers() bool {
	if o != nil && o.InitContainers != nil {
		return true
	}

	return false
}

// SetInitContainers gets a reference to the given []IoArgoprojWorkflowV1alpha1UserContainer and assigns it to the InitContainers field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetInitContainers(v []IoArgoprojWorkflowV1alpha1UserContainer) {
	o.InitContainers = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetInputs() IoArgoprojWorkflowV1alpha1Inputs {
	if o == nil || o.Inputs == nil {
		var ret IoArgoprojWorkflowV1alpha1Inputs
		return ret
	}
	return *o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetInputsOk() (*IoArgoprojWorkflowV1alpha1Inputs, bool) {
	if o == nil || o.Inputs == nil {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasInputs() bool {
	if o != nil && o.Inputs != nil {
		return true
	}

	return false
}

// SetInputs gets a reference to the given IoArgoprojWorkflowV1alpha1Inputs and assigns it to the Inputs field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetInputs(v IoArgoprojWorkflowV1alpha1Inputs) {
	o.Inputs = &v
}

// GetMemoize returns the Memoize field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetMemoize() IoArgoprojWorkflowV1alpha1Memoize {
	if o == nil || o.Memoize == nil {
		var ret IoArgoprojWorkflowV1alpha1Memoize
		return ret
	}
	return *o.Memoize
}

// GetMemoizeOk returns a tuple with the Memoize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetMemoizeOk() (*IoArgoprojWorkflowV1alpha1Memoize, bool) {
	if o == nil || o.Memoize == nil {
		return nil, false
	}
	return o.Memoize, true
}

// HasMemoize returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasMemoize() bool {
	if o != nil && o.Memoize != nil {
		return true
	}

	return false
}

// SetMemoize gets a reference to the given IoArgoprojWorkflowV1alpha1Memoize and assigns it to the Memoize field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetMemoize(v IoArgoprojWorkflowV1alpha1Memoize) {
	o.Memoize = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetMetadata() IoArgoprojWorkflowV1alpha1Metadata {
	if o == nil || o.Metadata == nil {
		var ret IoArgoprojWorkflowV1alpha1Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetMetadataOk() (*IoArgoprojWorkflowV1alpha1Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given IoArgoprojWorkflowV1alpha1Metadata and assigns it to the Metadata field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetMetadata(v IoArgoprojWorkflowV1alpha1Metadata) {
	o.Metadata = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetMetrics() IoArgoprojWorkflowV1alpha1Metrics {
	if o == nil || o.Metrics == nil {
		var ret IoArgoprojWorkflowV1alpha1Metrics
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetMetricsOk() (*IoArgoprojWorkflowV1alpha1Metrics, bool) {
	if o == nil || o.Metrics == nil {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasMetrics() bool {
	if o != nil && o.Metrics != nil {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given IoArgoprojWorkflowV1alpha1Metrics and assigns it to the Metrics field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetMetrics(v IoArgoprojWorkflowV1alpha1Metrics) {
	o.Metrics = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetName(v string) {
	o.Name = &v
}

// GetNodeSelector returns the NodeSelector field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetNodeSelector() map[string]string {
	if o == nil || o.NodeSelector == nil {
		var ret map[string]string
		return ret
	}
	return *o.NodeSelector
}

// GetNodeSelectorOk returns a tuple with the NodeSelector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetNodeSelectorOk() (*map[string]string, bool) {
	if o == nil || o.NodeSelector == nil {
		return nil, false
	}
	return o.NodeSelector, true
}

// HasNodeSelector returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasNodeSelector() bool {
	if o != nil && o.NodeSelector != nil {
		return true
	}

	return false
}

// SetNodeSelector gets a reference to the given map[string]string and assigns it to the NodeSelector field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetNodeSelector(v map[string]string) {
	o.NodeSelector = &v
}

// GetOutputs returns the Outputs field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetOutputs() IoArgoprojWorkflowV1alpha1Outputs {
	if o == nil || o.Outputs == nil {
		var ret IoArgoprojWorkflowV1alpha1Outputs
		return ret
	}
	return *o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetOutputsOk() (*IoArgoprojWorkflowV1alpha1Outputs, bool) {
	if o == nil || o.Outputs == nil {
		return nil, false
	}
	return o.Outputs, true
}

// HasOutputs returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasOutputs() bool {
	if o != nil && o.Outputs != nil {
		return true
	}

	return false
}

// SetOutputs gets a reference to the given IoArgoprojWorkflowV1alpha1Outputs and assigns it to the Outputs field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetOutputs(v IoArgoprojWorkflowV1alpha1Outputs) {
	o.Outputs = &v
}

// GetParallelism returns the Parallelism field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetParallelism() int32 {
	if o == nil || o.Parallelism == nil {
		var ret int32
		return ret
	}
	return *o.Parallelism
}

// GetParallelismOk returns a tuple with the Parallelism field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetParallelismOk() (*int32, bool) {
	if o == nil || o.Parallelism == nil {
		return nil, false
	}
	return o.Parallelism, true
}

// HasParallelism returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasParallelism() bool {
	if o != nil && o.Parallelism != nil {
		return true
	}

	return false
}

// SetParallelism gets a reference to the given int32 and assigns it to the Parallelism field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetParallelism(v int32) {
	o.Parallelism = &v
}

// GetPodSpecPatch returns the PodSpecPatch field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetPodSpecPatch() string {
	if o == nil || o.PodSpecPatch == nil {
		var ret string
		return ret
	}
	return *o.PodSpecPatch
}

// GetPodSpecPatchOk returns a tuple with the PodSpecPatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetPodSpecPatchOk() (*string, bool) {
	if o == nil || o.PodSpecPatch == nil {
		return nil, false
	}
	return o.PodSpecPatch, true
}

// HasPodSpecPatch returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasPodSpecPatch() bool {
	if o != nil && o.PodSpecPatch != nil {
		return true
	}

	return false
}

// SetPodSpecPatch gets a reference to the given string and assigns it to the PodSpecPatch field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetPodSpecPatch(v string) {
	o.PodSpecPatch = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetPriority() int32 {
	if o == nil || o.Priority == nil {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetPriorityOk() (*int32, bool) {
	if o == nil || o.Priority == nil {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasPriority() bool {
	if o != nil && o.Priority != nil {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetPriority(v int32) {
	o.Priority = &v
}

// GetPriorityClassName returns the PriorityClassName field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetPriorityClassName() string {
	if o == nil || o.PriorityClassName == nil {
		var ret string
		return ret
	}
	return *o.PriorityClassName
}

// GetPriorityClassNameOk returns a tuple with the PriorityClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetPriorityClassNameOk() (*string, bool) {
	if o == nil || o.PriorityClassName == nil {
		return nil, false
	}
	return o.PriorityClassName, true
}

// HasPriorityClassName returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasPriorityClassName() bool {
	if o != nil && o.PriorityClassName != nil {
		return true
	}

	return false
}

// SetPriorityClassName gets a reference to the given string and assigns it to the PriorityClassName field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetPriorityClassName(v string) {
	o.PriorityClassName = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetResource() IoArgoprojWorkflowV1alpha1ResourceTemplate {
	if o == nil || o.Resource == nil {
		var ret IoArgoprojWorkflowV1alpha1ResourceTemplate
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetResourceOk() (*IoArgoprojWorkflowV1alpha1ResourceTemplate, bool) {
	if o == nil || o.Resource == nil {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasResource() bool {
	if o != nil && o.Resource != nil {
		return true
	}

	return false
}

// SetResource gets a reference to the given IoArgoprojWorkflowV1alpha1ResourceTemplate and assigns it to the Resource field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetResource(v IoArgoprojWorkflowV1alpha1ResourceTemplate) {
	o.Resource = &v
}

// GetRetryStrategy returns the RetryStrategy field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetRetryStrategy() IoArgoprojWorkflowV1alpha1RetryStrategy {
	if o == nil || o.RetryStrategy == nil {
		var ret IoArgoprojWorkflowV1alpha1RetryStrategy
		return ret
	}
	return *o.RetryStrategy
}

// GetRetryStrategyOk returns a tuple with the RetryStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetRetryStrategyOk() (*IoArgoprojWorkflowV1alpha1RetryStrategy, bool) {
	if o == nil || o.RetryStrategy == nil {
		return nil, false
	}
	return o.RetryStrategy, true
}

// HasRetryStrategy returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasRetryStrategy() bool {
	if o != nil && o.RetryStrategy != nil {
		return true
	}

	return false
}

// SetRetryStrategy gets a reference to the given IoArgoprojWorkflowV1alpha1RetryStrategy and assigns it to the RetryStrategy field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetRetryStrategy(v IoArgoprojWorkflowV1alpha1RetryStrategy) {
	o.RetryStrategy = &v
}

// GetSchedulerName returns the SchedulerName field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSchedulerName() string {
	if o == nil || o.SchedulerName == nil {
		var ret string
		return ret
	}
	return *o.SchedulerName
}

// GetSchedulerNameOk returns a tuple with the SchedulerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSchedulerNameOk() (*string, bool) {
	if o == nil || o.SchedulerName == nil {
		return nil, false
	}
	return o.SchedulerName, true
}

// HasSchedulerName returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasSchedulerName() bool {
	if o != nil && o.SchedulerName != nil {
		return true
	}

	return false
}

// SetSchedulerName gets a reference to the given string and assigns it to the SchedulerName field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetSchedulerName(v string) {
	o.SchedulerName = &v
}

// GetScript returns the Script field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetScript() IoArgoprojWorkflowV1alpha1ScriptTemplate {
	if o == nil || o.Script == nil {
		var ret IoArgoprojWorkflowV1alpha1ScriptTemplate
		return ret
	}
	return *o.Script
}

// GetScriptOk returns a tuple with the Script field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetScriptOk() (*IoArgoprojWorkflowV1alpha1ScriptTemplate, bool) {
	if o == nil || o.Script == nil {
		return nil, false
	}
	return o.Script, true
}

// HasScript returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasScript() bool {
	if o != nil && o.Script != nil {
		return true
	}

	return false
}

// SetScript gets a reference to the given IoArgoprojWorkflowV1alpha1ScriptTemplate and assigns it to the Script field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetScript(v IoArgoprojWorkflowV1alpha1ScriptTemplate) {
	o.Script = &v
}

// GetSecurityContext returns the SecurityContext field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSecurityContext() IoK8sApiCoreV1PodSecurityContext {
	if o == nil || o.SecurityContext == nil {
		var ret IoK8sApiCoreV1PodSecurityContext
		return ret
	}
	return *o.SecurityContext
}

// GetSecurityContextOk returns a tuple with the SecurityContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSecurityContextOk() (*IoK8sApiCoreV1PodSecurityContext, bool) {
	if o == nil || o.SecurityContext == nil {
		return nil, false
	}
	return o.SecurityContext, true
}

// HasSecurityContext returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasSecurityContext() bool {
	if o != nil && o.SecurityContext != nil {
		return true
	}

	return false
}

// SetSecurityContext gets a reference to the given IoK8sApiCoreV1PodSecurityContext and assigns it to the SecurityContext field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetSecurityContext(v IoK8sApiCoreV1PodSecurityContext) {
	o.SecurityContext = &v
}

// GetServiceAccountName returns the ServiceAccountName field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetServiceAccountName() string {
	if o == nil || o.ServiceAccountName == nil {
		var ret string
		return ret
	}
	return *o.ServiceAccountName
}

// GetServiceAccountNameOk returns a tuple with the ServiceAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetServiceAccountNameOk() (*string, bool) {
	if o == nil || o.ServiceAccountName == nil {
		return nil, false
	}
	return o.ServiceAccountName, true
}

// HasServiceAccountName returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasServiceAccountName() bool {
	if o != nil && o.ServiceAccountName != nil {
		return true
	}

	return false
}

// SetServiceAccountName gets a reference to the given string and assigns it to the ServiceAccountName field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetServiceAccountName(v string) {
	o.ServiceAccountName = &v
}

// GetSidecars returns the Sidecars field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSidecars() []IoArgoprojWorkflowV1alpha1UserContainer {
	if o == nil || o.Sidecars == nil {
		var ret []IoArgoprojWorkflowV1alpha1UserContainer
		return ret
	}
	return *o.Sidecars
}

// GetSidecarsOk returns a tuple with the Sidecars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSidecarsOk() (*[]IoArgoprojWorkflowV1alpha1UserContainer, bool) {
	if o == nil || o.Sidecars == nil {
		return nil, false
	}
	return o.Sidecars, true
}

// HasSidecars returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasSidecars() bool {
	if o != nil && o.Sidecars != nil {
		return true
	}

	return false
}

// SetSidecars gets a reference to the given []IoArgoprojWorkflowV1alpha1UserContainer and assigns it to the Sidecars field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetSidecars(v []IoArgoprojWorkflowV1alpha1UserContainer) {
	o.Sidecars = &v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSteps() [][]IoArgoprojWorkflowV1alpha1WorkflowStep {
	if o == nil || o.Steps == nil {
		var ret [][]IoArgoprojWorkflowV1alpha1WorkflowStep
		return ret
	}
	return *o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetStepsOk() (*[][]IoArgoprojWorkflowV1alpha1WorkflowStep, bool) {
	if o == nil || o.Steps == nil {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasSteps() bool {
	if o != nil && o.Steps != nil {
		return true
	}

	return false
}

// SetSteps gets a reference to the given [][]IoArgoprojWorkflowV1alpha1WorkflowStep and assigns it to the Steps field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetSteps(v [][]IoArgoprojWorkflowV1alpha1WorkflowStep) {
	o.Steps = &v
}

// GetSuspend returns the Suspend field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSuspend() IoArgoprojWorkflowV1alpha1SuspendTemplate {
	if o == nil || o.Suspend == nil {
		var ret IoArgoprojWorkflowV1alpha1SuspendTemplate
		return ret
	}
	return *o.Suspend
}

// GetSuspendOk returns a tuple with the Suspend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSuspendOk() (*IoArgoprojWorkflowV1alpha1SuspendTemplate, bool) {
	if o == nil || o.Suspend == nil {
		return nil, false
	}
	return o.Suspend, true
}

// HasSuspend returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasSuspend() bool {
	if o != nil && o.Suspend != nil {
		return true
	}

	return false
}

// SetSuspend gets a reference to the given IoArgoprojWorkflowV1alpha1SuspendTemplate and assigns it to the Suspend field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetSuspend(v IoArgoprojWorkflowV1alpha1SuspendTemplate) {
	o.Suspend = &v
}

// GetSynchronization returns the Synchronization field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSynchronization() IoArgoprojWorkflowV1alpha1Synchronization {
	if o == nil || o.Synchronization == nil {
		var ret IoArgoprojWorkflowV1alpha1Synchronization
		return ret
	}
	return *o.Synchronization
}

// GetSynchronizationOk returns a tuple with the Synchronization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetSynchronizationOk() (*IoArgoprojWorkflowV1alpha1Synchronization, bool) {
	if o == nil || o.Synchronization == nil {
		return nil, false
	}
	return o.Synchronization, true
}

// HasSynchronization returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasSynchronization() bool {
	if o != nil && o.Synchronization != nil {
		return true
	}

	return false
}

// SetSynchronization gets a reference to the given IoArgoprojWorkflowV1alpha1Synchronization and assigns it to the Synchronization field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetSynchronization(v IoArgoprojWorkflowV1alpha1Synchronization) {
	o.Synchronization = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetTimeout() string {
	if o == nil || o.Timeout == nil {
		var ret string
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetTimeoutOk() (*string, bool) {
	if o == nil || o.Timeout == nil {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasTimeout() bool {
	if o != nil && o.Timeout != nil {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given string and assigns it to the Timeout field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetTimeout(v string) {
	o.Timeout = &v
}

// GetTolerations returns the Tolerations field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetTolerations() []IoK8sApiCoreV1Toleration {
	if o == nil || o.Tolerations == nil {
		var ret []IoK8sApiCoreV1Toleration
		return ret
	}
	return *o.Tolerations
}

// GetTolerationsOk returns a tuple with the Tolerations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetTolerationsOk() (*[]IoK8sApiCoreV1Toleration, bool) {
	if o == nil || o.Tolerations == nil {
		return nil, false
	}
	return o.Tolerations, true
}

// HasTolerations returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasTolerations() bool {
	if o != nil && o.Tolerations != nil {
		return true
	}

	return false
}

// SetTolerations gets a reference to the given []IoK8sApiCoreV1Toleration and assigns it to the Tolerations field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetTolerations(v []IoK8sApiCoreV1Toleration) {
	o.Tolerations = &v
}

// GetVolumes returns the Volumes field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Template) GetVolumes() []IoK8sApiCoreV1Volume {
	if o == nil || o.Volumes == nil {
		var ret []IoK8sApiCoreV1Volume
		return ret
	}
	return *o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) GetVolumesOk() (*[]IoK8sApiCoreV1Volume, bool) {
	if o == nil || o.Volumes == nil {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Template) HasVolumes() bool {
	if o != nil && o.Volumes != nil {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given []IoK8sApiCoreV1Volume and assigns it to the Volumes field.
func (o *IoArgoprojWorkflowV1alpha1Template) SetVolumes(v []IoK8sApiCoreV1Volume) {
	o.Volumes = &v
}

func (o IoArgoprojWorkflowV1alpha1Template) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ActiveDeadlineSeconds != nil {
		toSerialize["activeDeadlineSeconds"] = o.ActiveDeadlineSeconds
	}
	if o.Affinity != nil {
		toSerialize["affinity"] = o.Affinity
	}
	if o.ArchiveLocation != nil {
		toSerialize["archiveLocation"] = o.ArchiveLocation
	}
	if o.AutomountServiceAccountToken != nil {
		toSerialize["automountServiceAccountToken"] = o.AutomountServiceAccountToken
	}
	if o.Container != nil {
		toSerialize["container"] = o.Container
	}
	if o.ContainerSet != nil {
		toSerialize["containerSet"] = o.ContainerSet
	}
	if o.Daemon != nil {
		toSerialize["daemon"] = o.Daemon
	}
	if o.Dag != nil {
		toSerialize["dag"] = o.Dag
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Executor != nil {
		toSerialize["executor"] = o.Executor
	}
	if o.FailFast != nil {
		toSerialize["failFast"] = o.FailFast
	}
	if o.HostAliases != nil {
		toSerialize["hostAliases"] = o.HostAliases
	}
	if o.Http != nil {
		toSerialize["http"] = o.Http
	}
	if o.InitContainers != nil {
		toSerialize["initContainers"] = o.InitContainers
	}
	if o.Inputs != nil {
		toSerialize["inputs"] = o.Inputs
	}
	if o.Memoize != nil {
		toSerialize["memoize"] = o.Memoize
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Metrics != nil {
		toSerialize["metrics"] = o.Metrics
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.NodeSelector != nil {
		toSerialize["nodeSelector"] = o.NodeSelector
	}
	if o.Outputs != nil {
		toSerialize["outputs"] = o.Outputs
	}
	if o.Parallelism != nil {
		toSerialize["parallelism"] = o.Parallelism
	}
	if o.PodSpecPatch != nil {
		toSerialize["podSpecPatch"] = o.PodSpecPatch
	}
	if o.Priority != nil {
		toSerialize["priority"] = o.Priority
	}
	if o.PriorityClassName != nil {
		toSerialize["priorityClassName"] = o.PriorityClassName
	}
	if o.Resource != nil {
		toSerialize["resource"] = o.Resource
	}
	if o.RetryStrategy != nil {
		toSerialize["retryStrategy"] = o.RetryStrategy
	}
	if o.SchedulerName != nil {
		toSerialize["schedulerName"] = o.SchedulerName
	}
	if o.Script != nil {
		toSerialize["script"] = o.Script
	}
	if o.SecurityContext != nil {
		toSerialize["securityContext"] = o.SecurityContext
	}
	if o.ServiceAccountName != nil {
		toSerialize["serviceAccountName"] = o.ServiceAccountName
	}
	if o.Sidecars != nil {
		toSerialize["sidecars"] = o.Sidecars
	}
	if o.Steps != nil {
		toSerialize["steps"] = o.Steps
	}
	if o.Suspend != nil {
		toSerialize["suspend"] = o.Suspend
	}
	if o.Synchronization != nil {
		toSerialize["synchronization"] = o.Synchronization
	}
	if o.Timeout != nil {
		toSerialize["timeout"] = o.Timeout
	}
	if o.Tolerations != nil {
		toSerialize["tolerations"] = o.Tolerations
	}
	if o.Volumes != nil {
		toSerialize["volumes"] = o.Volumes
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojWorkflowV1alpha1Template struct {
	value *IoArgoprojWorkflowV1alpha1Template
	isSet bool
}

func (v NullableIoArgoprojWorkflowV1alpha1Template) Get() *IoArgoprojWorkflowV1alpha1Template {
	return v.value
}

func (v *NullableIoArgoprojWorkflowV1alpha1Template) Set(val *IoArgoprojWorkflowV1alpha1Template) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojWorkflowV1alpha1Template) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojWorkflowV1alpha1Template) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojWorkflowV1alpha1Template(val *IoArgoprojWorkflowV1alpha1Template) *NullableIoArgoprojWorkflowV1alpha1Template {
	return &NullableIoArgoprojWorkflowV1alpha1Template{value: val, isSet: true}
}

func (v NullableIoArgoprojWorkflowV1alpha1Template) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojWorkflowV1alpha1Template) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


