/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojWorkflowV1alpha1Outputs Outputs hold parameters, artifacts, and results from a step
type IoArgoprojWorkflowV1alpha1Outputs struct {
	// Artifacts holds the list of output artifacts produced by a step
	Artifacts *[]IoArgoprojWorkflowV1alpha1Artifact `json:"artifacts,omitempty"`
	// ExitCode holds the exit code of a script template
	ExitCode *string `json:"exitCode,omitempty"`
	// Parameters holds the list of output parameters produced by a step
	Parameters *[]IoArgoprojWorkflowV1alpha1Parameter `json:"parameters,omitempty"`
	// Result holds the result (stdout) of a script template
	Result *string `json:"result,omitempty"`
}

// NewIoArgoprojWorkflowV1alpha1Outputs instantiates a new IoArgoprojWorkflowV1alpha1Outputs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojWorkflowV1alpha1Outputs() *IoArgoprojWorkflowV1alpha1Outputs {
	this := IoArgoprojWorkflowV1alpha1Outputs{}
	return &this
}

// NewIoArgoprojWorkflowV1alpha1OutputsWithDefaults instantiates a new IoArgoprojWorkflowV1alpha1Outputs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojWorkflowV1alpha1OutputsWithDefaults() *IoArgoprojWorkflowV1alpha1Outputs {
	this := IoArgoprojWorkflowV1alpha1Outputs{}
	return &this
}

// GetArtifacts returns the Artifacts field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetArtifacts() []IoArgoprojWorkflowV1alpha1Artifact {
	if o == nil || o.Artifacts == nil {
		var ret []IoArgoprojWorkflowV1alpha1Artifact
		return ret
	}
	return *o.Artifacts
}

// GetArtifactsOk returns a tuple with the Artifacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetArtifactsOk() (*[]IoArgoprojWorkflowV1alpha1Artifact, bool) {
	if o == nil || o.Artifacts == nil {
		return nil, false
	}
	return o.Artifacts, true
}

// HasArtifacts returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) HasArtifacts() bool {
	if o != nil && o.Artifacts != nil {
		return true
	}

	return false
}

// SetArtifacts gets a reference to the given []IoArgoprojWorkflowV1alpha1Artifact and assigns it to the Artifacts field.
func (o *IoArgoprojWorkflowV1alpha1Outputs) SetArtifacts(v []IoArgoprojWorkflowV1alpha1Artifact) {
	o.Artifacts = &v
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetExitCode() string {
	if o == nil || o.ExitCode == nil {
		var ret string
		return ret
	}
	return *o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetExitCodeOk() (*string, bool) {
	if o == nil || o.ExitCode == nil {
		return nil, false
	}
	return o.ExitCode, true
}

// HasExitCode returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) HasExitCode() bool {
	if o != nil && o.ExitCode != nil {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given string and assigns it to the ExitCode field.
func (o *IoArgoprojWorkflowV1alpha1Outputs) SetExitCode(v string) {
	o.ExitCode = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetParameters() []IoArgoprojWorkflowV1alpha1Parameter {
	if o == nil || o.Parameters == nil {
		var ret []IoArgoprojWorkflowV1alpha1Parameter
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetParametersOk() (*[]IoArgoprojWorkflowV1alpha1Parameter, bool) {
	if o == nil || o.Parameters == nil {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) HasParameters() bool {
	if o != nil && o.Parameters != nil {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []IoArgoprojWorkflowV1alpha1Parameter and assigns it to the Parameters field.
func (o *IoArgoprojWorkflowV1alpha1Outputs) SetParameters(v []IoArgoprojWorkflowV1alpha1Parameter) {
	o.Parameters = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetResult() string {
	if o == nil || o.Result == nil {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) GetResultOk() (*string, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1Outputs) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *IoArgoprojWorkflowV1alpha1Outputs) SetResult(v string) {
	o.Result = &v
}

func (o IoArgoprojWorkflowV1alpha1Outputs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Artifacts != nil {
		toSerialize["artifacts"] = o.Artifacts
	}
	if o.ExitCode != nil {
		toSerialize["exitCode"] = o.ExitCode
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojWorkflowV1alpha1Outputs struct {
	value *IoArgoprojWorkflowV1alpha1Outputs
	isSet bool
}

func (v NullableIoArgoprojWorkflowV1alpha1Outputs) Get() *IoArgoprojWorkflowV1alpha1Outputs {
	return v.value
}

func (v *NullableIoArgoprojWorkflowV1alpha1Outputs) Set(val *IoArgoprojWorkflowV1alpha1Outputs) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojWorkflowV1alpha1Outputs) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojWorkflowV1alpha1Outputs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojWorkflowV1alpha1Outputs(val *IoArgoprojWorkflowV1alpha1Outputs) *NullableIoArgoprojWorkflowV1alpha1Outputs {
	return &NullableIoArgoprojWorkflowV1alpha1Outputs{value: val, isSet: true}
}

func (v NullableIoArgoprojWorkflowV1alpha1Outputs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojWorkflowV1alpha1Outputs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


