/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojWorkflowV1alpha1OSSLifecycleRule OSSLifecycleRule specifies how to manage bucket's lifecycle
type IoArgoprojWorkflowV1alpha1OSSLifecycleRule struct {
	// MarkDeletionAfterDays is the number of days before we delete objects in the bucket
	MarkDeletionAfterDays *int32 `json:"markDeletionAfterDays,omitempty"`
	// MarkInfrequentAccessAfterDays is the number of days before we convert the objects in the bucket to Infrequent Access (IA) storage type
	MarkInfrequentAccessAfterDays *int32 `json:"markInfrequentAccessAfterDays,omitempty"`
}

// NewIoArgoprojWorkflowV1alpha1OSSLifecycleRule instantiates a new IoArgoprojWorkflowV1alpha1OSSLifecycleRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojWorkflowV1alpha1OSSLifecycleRule() *IoArgoprojWorkflowV1alpha1OSSLifecycleRule {
	this := IoArgoprojWorkflowV1alpha1OSSLifecycleRule{}
	return &this
}

// NewIoArgoprojWorkflowV1alpha1OSSLifecycleRuleWithDefaults instantiates a new IoArgoprojWorkflowV1alpha1OSSLifecycleRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojWorkflowV1alpha1OSSLifecycleRuleWithDefaults() *IoArgoprojWorkflowV1alpha1OSSLifecycleRule {
	this := IoArgoprojWorkflowV1alpha1OSSLifecycleRule{}
	return &this
}

// GetMarkDeletionAfterDays returns the MarkDeletionAfterDays field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) GetMarkDeletionAfterDays() int32 {
	if o == nil || o.MarkDeletionAfterDays == nil {
		var ret int32
		return ret
	}
	return *o.MarkDeletionAfterDays
}

// GetMarkDeletionAfterDaysOk returns a tuple with the MarkDeletionAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) GetMarkDeletionAfterDaysOk() (*int32, bool) {
	if o == nil || o.MarkDeletionAfterDays == nil {
		return nil, false
	}
	return o.MarkDeletionAfterDays, true
}

// HasMarkDeletionAfterDays returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) HasMarkDeletionAfterDays() bool {
	if o != nil && o.MarkDeletionAfterDays != nil {
		return true
	}

	return false
}

// SetMarkDeletionAfterDays gets a reference to the given int32 and assigns it to the MarkDeletionAfterDays field.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) SetMarkDeletionAfterDays(v int32) {
	o.MarkDeletionAfterDays = &v
}

// GetMarkInfrequentAccessAfterDays returns the MarkInfrequentAccessAfterDays field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) GetMarkInfrequentAccessAfterDays() int32 {
	if o == nil || o.MarkInfrequentAccessAfterDays == nil {
		var ret int32
		return ret
	}
	return *o.MarkInfrequentAccessAfterDays
}

// GetMarkInfrequentAccessAfterDaysOk returns a tuple with the MarkInfrequentAccessAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) GetMarkInfrequentAccessAfterDaysOk() (*int32, bool) {
	if o == nil || o.MarkInfrequentAccessAfterDays == nil {
		return nil, false
	}
	return o.MarkInfrequentAccessAfterDays, true
}

// HasMarkInfrequentAccessAfterDays returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) HasMarkInfrequentAccessAfterDays() bool {
	if o != nil && o.MarkInfrequentAccessAfterDays != nil {
		return true
	}

	return false
}

// SetMarkInfrequentAccessAfterDays gets a reference to the given int32 and assigns it to the MarkInfrequentAccessAfterDays field.
func (o *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) SetMarkInfrequentAccessAfterDays(v int32) {
	o.MarkInfrequentAccessAfterDays = &v
}

func (o IoArgoprojWorkflowV1alpha1OSSLifecycleRule) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MarkDeletionAfterDays != nil {
		toSerialize["markDeletionAfterDays"] = o.MarkDeletionAfterDays
	}
	if o.MarkInfrequentAccessAfterDays != nil {
		toSerialize["markInfrequentAccessAfterDays"] = o.MarkInfrequentAccessAfterDays
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule struct {
	value *IoArgoprojWorkflowV1alpha1OSSLifecycleRule
	isSet bool
}

func (v NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule) Get() *IoArgoprojWorkflowV1alpha1OSSLifecycleRule {
	return v.value
}

func (v *NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule) Set(val *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule(val *IoArgoprojWorkflowV1alpha1OSSLifecycleRule) *NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule {
	return &NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule{value: val, isSet: true}
}

func (v NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojWorkflowV1alpha1OSSLifecycleRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


