/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojWorkflowV1alpha1TTLStrategy TTLStrategy is the strategy for the time to live depending on if the workflow succeeded or failed
type IoArgoprojWorkflowV1alpha1TTLStrategy struct {
	// SecondsAfterCompletion is the number of seconds to live after completion
	SecondsAfterCompletion *int32 `json:"secondsAfterCompletion,omitempty"`
	// SecondsAfterFailure is the number of seconds to live after failure
	SecondsAfterFailure *int32 `json:"secondsAfterFailure,omitempty"`
	// SecondsAfterSuccess is the number of seconds to live after success
	SecondsAfterSuccess *int32 `json:"secondsAfterSuccess,omitempty"`
}

// NewIoArgoprojWorkflowV1alpha1TTLStrategy instantiates a new IoArgoprojWorkflowV1alpha1TTLStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojWorkflowV1alpha1TTLStrategy() *IoArgoprojWorkflowV1alpha1TTLStrategy {
	this := IoArgoprojWorkflowV1alpha1TTLStrategy{}
	return &this
}

// NewIoArgoprojWorkflowV1alpha1TTLStrategyWithDefaults instantiates a new IoArgoprojWorkflowV1alpha1TTLStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojWorkflowV1alpha1TTLStrategyWithDefaults() *IoArgoprojWorkflowV1alpha1TTLStrategy {
	this := IoArgoprojWorkflowV1alpha1TTLStrategy{}
	return &this
}

// GetSecondsAfterCompletion returns the SecondsAfterCompletion field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) GetSecondsAfterCompletion() int32 {
	if o == nil || o.SecondsAfterCompletion == nil {
		var ret int32
		return ret
	}
	return *o.SecondsAfterCompletion
}

// GetSecondsAfterCompletionOk returns a tuple with the SecondsAfterCompletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) GetSecondsAfterCompletionOk() (*int32, bool) {
	if o == nil || o.SecondsAfterCompletion == nil {
		return nil, false
	}
	return o.SecondsAfterCompletion, true
}

// HasSecondsAfterCompletion returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) HasSecondsAfterCompletion() bool {
	if o != nil && o.SecondsAfterCompletion != nil {
		return true
	}

	return false
}

// SetSecondsAfterCompletion gets a reference to the given int32 and assigns it to the SecondsAfterCompletion field.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) SetSecondsAfterCompletion(v int32) {
	o.SecondsAfterCompletion = &v
}

// GetSecondsAfterFailure returns the SecondsAfterFailure field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) GetSecondsAfterFailure() int32 {
	if o == nil || o.SecondsAfterFailure == nil {
		var ret int32
		return ret
	}
	return *o.SecondsAfterFailure
}

// GetSecondsAfterFailureOk returns a tuple with the SecondsAfterFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) GetSecondsAfterFailureOk() (*int32, bool) {
	if o == nil || o.SecondsAfterFailure == nil {
		return nil, false
	}
	return o.SecondsAfterFailure, true
}

// HasSecondsAfterFailure returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) HasSecondsAfterFailure() bool {
	if o != nil && o.SecondsAfterFailure != nil {
		return true
	}

	return false
}

// SetSecondsAfterFailure gets a reference to the given int32 and assigns it to the SecondsAfterFailure field.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) SetSecondsAfterFailure(v int32) {
	o.SecondsAfterFailure = &v
}

// GetSecondsAfterSuccess returns the SecondsAfterSuccess field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) GetSecondsAfterSuccess() int32 {
	if o == nil || o.SecondsAfterSuccess == nil {
		var ret int32
		return ret
	}
	return *o.SecondsAfterSuccess
}

// GetSecondsAfterSuccessOk returns a tuple with the SecondsAfterSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) GetSecondsAfterSuccessOk() (*int32, bool) {
	if o == nil || o.SecondsAfterSuccess == nil {
		return nil, false
	}
	return o.SecondsAfterSuccess, true
}

// HasSecondsAfterSuccess returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) HasSecondsAfterSuccess() bool {
	if o != nil && o.SecondsAfterSuccess != nil {
		return true
	}

	return false
}

// SetSecondsAfterSuccess gets a reference to the given int32 and assigns it to the SecondsAfterSuccess field.
func (o *IoArgoprojWorkflowV1alpha1TTLStrategy) SetSecondsAfterSuccess(v int32) {
	o.SecondsAfterSuccess = &v
}

func (o IoArgoprojWorkflowV1alpha1TTLStrategy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SecondsAfterCompletion != nil {
		toSerialize["secondsAfterCompletion"] = o.SecondsAfterCompletion
	}
	if o.SecondsAfterFailure != nil {
		toSerialize["secondsAfterFailure"] = o.SecondsAfterFailure
	}
	if o.SecondsAfterSuccess != nil {
		toSerialize["secondsAfterSuccess"] = o.SecondsAfterSuccess
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojWorkflowV1alpha1TTLStrategy struct {
	value *IoArgoprojWorkflowV1alpha1TTLStrategy
	isSet bool
}

func (v NullableIoArgoprojWorkflowV1alpha1TTLStrategy) Get() *IoArgoprojWorkflowV1alpha1TTLStrategy {
	return v.value
}

func (v *NullableIoArgoprojWorkflowV1alpha1TTLStrategy) Set(val *IoArgoprojWorkflowV1alpha1TTLStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojWorkflowV1alpha1TTLStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojWorkflowV1alpha1TTLStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojWorkflowV1alpha1TTLStrategy(val *IoArgoprojWorkflowV1alpha1TTLStrategy) *NullableIoArgoprojWorkflowV1alpha1TTLStrategy {
	return &NullableIoArgoprojWorkflowV1alpha1TTLStrategy{value: val, isSet: true}
}

func (v NullableIoArgoprojWorkflowV1alpha1TTLStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojWorkflowV1alpha1TTLStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


