/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec PodDisruptionBudgetSpec is a description of a PodDisruptionBudget.
type IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec struct {
	MaxUnavailable *string `json:"maxUnavailable,omitempty"`
	MinAvailable *string `json:"minAvailable,omitempty"`
	Selector *IoK8sApimachineryPkgApisMetaV1LabelSelector `json:"selector,omitempty"`
}

// NewIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec instantiates a new IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec() *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec {
	this := IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec{}
	return &this
}

// NewIoK8sApiPolicyV1beta1PodDisruptionBudgetSpecWithDefaults instantiates a new IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoK8sApiPolicyV1beta1PodDisruptionBudgetSpecWithDefaults() *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec {
	this := IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec{}
	return &this
}

// GetMaxUnavailable returns the MaxUnavailable field value if set, zero value otherwise.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) GetMaxUnavailable() string {
	if o == nil || o.MaxUnavailable == nil {
		var ret string
		return ret
	}
	return *o.MaxUnavailable
}

// GetMaxUnavailableOk returns a tuple with the MaxUnavailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) GetMaxUnavailableOk() (*string, bool) {
	if o == nil || o.MaxUnavailable == nil {
		return nil, false
	}
	return o.MaxUnavailable, true
}

// HasMaxUnavailable returns a boolean if a field has been set.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) HasMaxUnavailable() bool {
	if o != nil && o.MaxUnavailable != nil {
		return true
	}

	return false
}

// SetMaxUnavailable gets a reference to the given string and assigns it to the MaxUnavailable field.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) SetMaxUnavailable(v string) {
	o.MaxUnavailable = &v
}

// GetMinAvailable returns the MinAvailable field value if set, zero value otherwise.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) GetMinAvailable() string {
	if o == nil || o.MinAvailable == nil {
		var ret string
		return ret
	}
	return *o.MinAvailable
}

// GetMinAvailableOk returns a tuple with the MinAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) GetMinAvailableOk() (*string, bool) {
	if o == nil || o.MinAvailable == nil {
		return nil, false
	}
	return o.MinAvailable, true
}

// HasMinAvailable returns a boolean if a field has been set.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) HasMinAvailable() bool {
	if o != nil && o.MinAvailable != nil {
		return true
	}

	return false
}

// SetMinAvailable gets a reference to the given string and assigns it to the MinAvailable field.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) SetMinAvailable(v string) {
	o.MinAvailable = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) GetSelector() IoK8sApimachineryPkgApisMetaV1LabelSelector {
	if o == nil || o.Selector == nil {
		var ret IoK8sApimachineryPkgApisMetaV1LabelSelector
		return ret
	}
	return *o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) GetSelectorOk() (*IoK8sApimachineryPkgApisMetaV1LabelSelector, bool) {
	if o == nil || o.Selector == nil {
		return nil, false
	}
	return o.Selector, true
}

// HasSelector returns a boolean if a field has been set.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) HasSelector() bool {
	if o != nil && o.Selector != nil {
		return true
	}

	return false
}

// SetSelector gets a reference to the given IoK8sApimachineryPkgApisMetaV1LabelSelector and assigns it to the Selector field.
func (o *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) SetSelector(v IoK8sApimachineryPkgApisMetaV1LabelSelector) {
	o.Selector = &v
}

func (o IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MaxUnavailable != nil {
		toSerialize["maxUnavailable"] = o.MaxUnavailable
	}
	if o.MinAvailable != nil {
		toSerialize["minAvailable"] = o.MinAvailable
	}
	if o.Selector != nil {
		toSerialize["selector"] = o.Selector
	}
	return json.Marshal(toSerialize)
}

type NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec struct {
	value *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec
	isSet bool
}

func (v NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) Get() *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec {
	return v.value
}

func (v *NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) Set(val *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec(val *IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) *NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec {
	return &NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec{value: val, isSet: true}
}

func (v NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoK8sApiPolicyV1beta1PodDisruptionBudgetSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


