/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojEventsV1alpha1FileArtifact struct for IoArgoprojEventsV1alpha1FileArtifact
type IoArgoprojEventsV1alpha1FileArtifact struct {
	Path *string `json:"path,omitempty"`
}

// NewIoArgoprojEventsV1alpha1FileArtifact instantiates a new IoArgoprojEventsV1alpha1FileArtifact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojEventsV1alpha1FileArtifact() *IoArgoprojEventsV1alpha1FileArtifact {
	this := IoArgoprojEventsV1alpha1FileArtifact{}
	return &this
}

// NewIoArgoprojEventsV1alpha1FileArtifactWithDefaults instantiates a new IoArgoprojEventsV1alpha1FileArtifact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojEventsV1alpha1FileArtifactWithDefaults() *IoArgoprojEventsV1alpha1FileArtifact {
	this := IoArgoprojEventsV1alpha1FileArtifact{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *IoArgoprojEventsV1alpha1FileArtifact) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojEventsV1alpha1FileArtifact) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *IoArgoprojEventsV1alpha1FileArtifact) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *IoArgoprojEventsV1alpha1FileArtifact) SetPath(v string) {
	o.Path = &v
}

func (o IoArgoprojEventsV1alpha1FileArtifact) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojEventsV1alpha1FileArtifact struct {
	value *IoArgoprojEventsV1alpha1FileArtifact
	isSet bool
}

func (v NullableIoArgoprojEventsV1alpha1FileArtifact) Get() *IoArgoprojEventsV1alpha1FileArtifact {
	return v.value
}

func (v *NullableIoArgoprojEventsV1alpha1FileArtifact) Set(val *IoArgoprojEventsV1alpha1FileArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojEventsV1alpha1FileArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojEventsV1alpha1FileArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojEventsV1alpha1FileArtifact(val *IoArgoprojEventsV1alpha1FileArtifact) *NullableIoArgoprojEventsV1alpha1FileArtifact {
	return &NullableIoArgoprojEventsV1alpha1FileArtifact{value: val, isSet: true}
}

func (v NullableIoArgoprojEventsV1alpha1FileArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojEventsV1alpha1FileArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


