/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoK8sApiCoreV1StorageOSVolumeSource Represents a StorageOS persistent volume resource.
type IoK8sApiCoreV1StorageOSVolumeSource struct {
	// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
	FsType *string `json:"fsType,omitempty"`
	// Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
	ReadOnly *bool `json:"readOnly,omitempty"`
	SecretRef *IoK8sApiCoreV1LocalObjectReference `json:"secretRef,omitempty"`
	// VolumeName is the human-readable name of the StorageOS volume.  Volume names are only unique within a namespace.
	VolumeName *string `json:"volumeName,omitempty"`
	// VolumeNamespace specifies the scope of the volume within StorageOS.  If no namespace is specified then the Pod's namespace will be used.  This allows the Kubernetes name scoping to be mirrored within StorageOS for tighter integration. Set VolumeName to any name to override the default behaviour. Set to \"default\" if you are not using namespaces within StorageOS. Namespaces that do not pre-exist within StorageOS will be created.
	VolumeNamespace *string `json:"volumeNamespace,omitempty"`
}

// NewIoK8sApiCoreV1StorageOSVolumeSource instantiates a new IoK8sApiCoreV1StorageOSVolumeSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoK8sApiCoreV1StorageOSVolumeSource() *IoK8sApiCoreV1StorageOSVolumeSource {
	this := IoK8sApiCoreV1StorageOSVolumeSource{}
	return &this
}

// NewIoK8sApiCoreV1StorageOSVolumeSourceWithDefaults instantiates a new IoK8sApiCoreV1StorageOSVolumeSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoK8sApiCoreV1StorageOSVolumeSourceWithDefaults() *IoK8sApiCoreV1StorageOSVolumeSource {
	this := IoK8sApiCoreV1StorageOSVolumeSource{}
	return &this
}

// GetFsType returns the FsType field value if set, zero value otherwise.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetFsType() string {
	if o == nil || o.FsType == nil {
		var ret string
		return ret
	}
	return *o.FsType
}

// GetFsTypeOk returns a tuple with the FsType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetFsTypeOk() (*string, bool) {
	if o == nil || o.FsType == nil {
		return nil, false
	}
	return o.FsType, true
}

// HasFsType returns a boolean if a field has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) HasFsType() bool {
	if o != nil && o.FsType != nil {
		return true
	}

	return false
}

// SetFsType gets a reference to the given string and assigns it to the FsType field.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) SetFsType(v string) {
	o.FsType = &v
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetReadOnly() bool {
	if o == nil || o.ReadOnly == nil {
		var ret bool
		return ret
	}
	return *o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetReadOnlyOk() (*bool, bool) {
	if o == nil || o.ReadOnly == nil {
		return nil, false
	}
	return o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) HasReadOnly() bool {
	if o != nil && o.ReadOnly != nil {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given bool and assigns it to the ReadOnly field.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) SetReadOnly(v bool) {
	o.ReadOnly = &v
}

// GetSecretRef returns the SecretRef field value if set, zero value otherwise.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetSecretRef() IoK8sApiCoreV1LocalObjectReference {
	if o == nil || o.SecretRef == nil {
		var ret IoK8sApiCoreV1LocalObjectReference
		return ret
	}
	return *o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetSecretRefOk() (*IoK8sApiCoreV1LocalObjectReference, bool) {
	if o == nil || o.SecretRef == nil {
		return nil, false
	}
	return o.SecretRef, true
}

// HasSecretRef returns a boolean if a field has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) HasSecretRef() bool {
	if o != nil && o.SecretRef != nil {
		return true
	}

	return false
}

// SetSecretRef gets a reference to the given IoK8sApiCoreV1LocalObjectReference and assigns it to the SecretRef field.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) SetSecretRef(v IoK8sApiCoreV1LocalObjectReference) {
	o.SecretRef = &v
}

// GetVolumeName returns the VolumeName field value if set, zero value otherwise.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetVolumeName() string {
	if o == nil || o.VolumeName == nil {
		var ret string
		return ret
	}
	return *o.VolumeName
}

// GetVolumeNameOk returns a tuple with the VolumeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetVolumeNameOk() (*string, bool) {
	if o == nil || o.VolumeName == nil {
		return nil, false
	}
	return o.VolumeName, true
}

// HasVolumeName returns a boolean if a field has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) HasVolumeName() bool {
	if o != nil && o.VolumeName != nil {
		return true
	}

	return false
}

// SetVolumeName gets a reference to the given string and assigns it to the VolumeName field.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) SetVolumeName(v string) {
	o.VolumeName = &v
}

// GetVolumeNamespace returns the VolumeNamespace field value if set, zero value otherwise.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetVolumeNamespace() string {
	if o == nil || o.VolumeNamespace == nil {
		var ret string
		return ret
	}
	return *o.VolumeNamespace
}

// GetVolumeNamespaceOk returns a tuple with the VolumeNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) GetVolumeNamespaceOk() (*string, bool) {
	if o == nil || o.VolumeNamespace == nil {
		return nil, false
	}
	return o.VolumeNamespace, true
}

// HasVolumeNamespace returns a boolean if a field has been set.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) HasVolumeNamespace() bool {
	if o != nil && o.VolumeNamespace != nil {
		return true
	}

	return false
}

// SetVolumeNamespace gets a reference to the given string and assigns it to the VolumeNamespace field.
func (o *IoK8sApiCoreV1StorageOSVolumeSource) SetVolumeNamespace(v string) {
	o.VolumeNamespace = &v
}

func (o IoK8sApiCoreV1StorageOSVolumeSource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FsType != nil {
		toSerialize["fsType"] = o.FsType
	}
	if o.ReadOnly != nil {
		toSerialize["readOnly"] = o.ReadOnly
	}
	if o.SecretRef != nil {
		toSerialize["secretRef"] = o.SecretRef
	}
	if o.VolumeName != nil {
		toSerialize["volumeName"] = o.VolumeName
	}
	if o.VolumeNamespace != nil {
		toSerialize["volumeNamespace"] = o.VolumeNamespace
	}
	return json.Marshal(toSerialize)
}

type NullableIoK8sApiCoreV1StorageOSVolumeSource struct {
	value *IoK8sApiCoreV1StorageOSVolumeSource
	isSet bool
}

func (v NullableIoK8sApiCoreV1StorageOSVolumeSource) Get() *IoK8sApiCoreV1StorageOSVolumeSource {
	return v.value
}

func (v *NullableIoK8sApiCoreV1StorageOSVolumeSource) Set(val *IoK8sApiCoreV1StorageOSVolumeSource) {
	v.value = val
	v.isSet = true
}

func (v NullableIoK8sApiCoreV1StorageOSVolumeSource) IsSet() bool {
	return v.isSet
}

func (v *NullableIoK8sApiCoreV1StorageOSVolumeSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoK8sApiCoreV1StorageOSVolumeSource(val *IoK8sApiCoreV1StorageOSVolumeSource) *NullableIoK8sApiCoreV1StorageOSVolumeSource {
	return &NullableIoK8sApiCoreV1StorageOSVolumeSource{value: val, isSet: true}
}

func (v NullableIoK8sApiCoreV1StorageOSVolumeSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoK8sApiCoreV1StorageOSVolumeSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


