/*
Argo Server API

You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`

API version: VERSION
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IoArgoprojWorkflowV1alpha1ContainerSetTemplate struct for IoArgoprojWorkflowV1alpha1ContainerSetTemplate
type IoArgoprojWorkflowV1alpha1ContainerSetTemplate struct {
	Containers []IoArgoprojWorkflowV1alpha1ContainerNode `json:"containers"`
	VolumeMounts *[]IoK8sApiCoreV1VolumeMount `json:"volumeMounts,omitempty"`
}

// NewIoArgoprojWorkflowV1alpha1ContainerSetTemplate instantiates a new IoArgoprojWorkflowV1alpha1ContainerSetTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIoArgoprojWorkflowV1alpha1ContainerSetTemplate(containers []IoArgoprojWorkflowV1alpha1ContainerNode) *IoArgoprojWorkflowV1alpha1ContainerSetTemplate {
	this := IoArgoprojWorkflowV1alpha1ContainerSetTemplate{}
	this.Containers = containers
	return &this
}

// NewIoArgoprojWorkflowV1alpha1ContainerSetTemplateWithDefaults instantiates a new IoArgoprojWorkflowV1alpha1ContainerSetTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIoArgoprojWorkflowV1alpha1ContainerSetTemplateWithDefaults() *IoArgoprojWorkflowV1alpha1ContainerSetTemplate {
	this := IoArgoprojWorkflowV1alpha1ContainerSetTemplate{}
	return &this
}

// GetContainers returns the Containers field value
func (o *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) GetContainers() []IoArgoprojWorkflowV1alpha1ContainerNode {
	if o == nil {
		var ret []IoArgoprojWorkflowV1alpha1ContainerNode
		return ret
	}

	return o.Containers
}

// GetContainersOk returns a tuple with the Containers field value
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) GetContainersOk() (*[]IoArgoprojWorkflowV1alpha1ContainerNode, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Containers, true
}

// SetContainers sets field value
func (o *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) SetContainers(v []IoArgoprojWorkflowV1alpha1ContainerNode) {
	o.Containers = v
}

// GetVolumeMounts returns the VolumeMounts field value if set, zero value otherwise.
func (o *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) GetVolumeMounts() []IoK8sApiCoreV1VolumeMount {
	if o == nil || o.VolumeMounts == nil {
		var ret []IoK8sApiCoreV1VolumeMount
		return ret
	}
	return *o.VolumeMounts
}

// GetVolumeMountsOk returns a tuple with the VolumeMounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) GetVolumeMountsOk() (*[]IoK8sApiCoreV1VolumeMount, bool) {
	if o == nil || o.VolumeMounts == nil {
		return nil, false
	}
	return o.VolumeMounts, true
}

// HasVolumeMounts returns a boolean if a field has been set.
func (o *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) HasVolumeMounts() bool {
	if o != nil && o.VolumeMounts != nil {
		return true
	}

	return false
}

// SetVolumeMounts gets a reference to the given []IoK8sApiCoreV1VolumeMount and assigns it to the VolumeMounts field.
func (o *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) SetVolumeMounts(v []IoK8sApiCoreV1VolumeMount) {
	o.VolumeMounts = &v
}

func (o IoArgoprojWorkflowV1alpha1ContainerSetTemplate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["containers"] = o.Containers
	}
	if o.VolumeMounts != nil {
		toSerialize["volumeMounts"] = o.VolumeMounts
	}
	return json.Marshal(toSerialize)
}

type NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate struct {
	value *IoArgoprojWorkflowV1alpha1ContainerSetTemplate
	isSet bool
}

func (v NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate) Get() *IoArgoprojWorkflowV1alpha1ContainerSetTemplate {
	return v.value
}

func (v *NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate) Set(val *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate(val *IoArgoprojWorkflowV1alpha1ContainerSetTemplate) *NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate {
	return &NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate{value: val, isSet: true}
}

func (v NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIoArgoprojWorkflowV1alpha1ContainerSetTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


